name: haptics_ringtone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  vibration: ^3.1.3
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  flutter_speed_dial: ^7.0.0
  simple_animated_icon: ^1.1.0
  share_plus: ^9.0.0
  file_selector: ^1.0.3
  url_launcher: ^6.3.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true
